name: Test
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  #  This action cleans up previously running instances of a workflow on the same branch. This accomplishes
  #  the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in
  #  most CI systems but currently not possible with GitHub actions.
  cleanup_runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  test_with_provenance_release:
    runs-on: ubuntu-latest
    name: Test with provenance release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Smart Contract Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provenance_version: "v1.11.1"
          test_script: "./smart-contract-action/test/test.sh"
          generate_proposals: true

  test_with_provenance_pr:
    runs-on: ubuntu-latest
    name: Test with provenance pull request
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Smart Contract Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provenance_version: "dwedul/update-swagger-bank"
          test_script: "./smart-contract-action/test/test.sh"
          generate_proposals: true